---
# Before running this playbook, run this command in the terminal:
# export api_key=XXXXXXXXXxxxxxXXXXxxXxxXXxXxXXxX
# (insert your own api key from your datadog env)
# (from the events home page of your dash-baord, left side menu bar, hover over 'integrations' and select 'APIs')

- hosts: datadog # in this case I am not using local host
                    # I am specifying the group on my hosts file called 'datadog'
                    # all the tasks below will be done using those server's resources

  #become: true # elevate the ansible_ssh_user's privileges to root (password-less)

  vars: # variables can be anything, but there are some specific ones to use like ansible_ssh_user, etc...
    myteam: anthony-and-son-team # change this to your team name!!!
    #ansible_ssh_user: ec2-user # ec2-user is the default user that comes with image:"ami-4836a428"
                               # this will get used when the playbook connects to your aws servers through ssh
    #ansible_ssh_private_key_file: datadog.pem # instead of giving an ssh password, the playbook will pass the .pem file (same one used to create the aws servers) for authorization
  tasks:

  - name: ensure package cache is up to date
    apt: update_cache=yes cache_valid_time=3600

  - name: install web server
    apt: pkg=apache2 state=present

  - name: ensure package cache is up to date
    apt: update_cache=yes cache_valid_time=3600

  - name: load apache # with this task, ansible is doing what I would do with apt-get install httpd
    package: # 'package' module is a python script that determines your flavor of linux
             # to decide if it should use 'yum' or 'apt-get', etc... in order to do download a package
      name: apache2 # this is the name of the package to be installed by 'yum' or 'apt-get'

  - name: start apache
    service: # 'service' module allows you to specify a service already installed on the systems (httpd in this case)
             # and do something to it (start it, enable, it etc...)
      name: apache2
      state: started

  - name: enable apache
    service:
      name: apache2
      enabled: yes

  - name: install index page
    template: src=datadog.html.j2 dest=/var/www/html/index.html
